### ISSUE TITLE
Context Menu Label

### ISSUE THREAD

**Issue by Alecton4** [hall/draw#3]
Maybe changing the label in the context menu to something like "Draw: Edit Current Line" for easier identification.

![image](https://user-images.githubusercontent.com/43232804/217820216-e6d14960-b512-460d-8c69-f7dc5454178e.png)

**Comment by hall** [comment]
Yep -- good point. I guess I don't really use the context menu so never noticed :sweat_smile: 

Interestingly enough, [VSCode prepends the `category` (`Draw`, in our case) in the Command Palette but _not_ in the editor context menu](https://code.visualstudio.com/api/references/contribution-points#contributes.commands)

> The Command Palette . . . prefixes commands with their category, allowing for easy grouping. . . . The editor context menu, on the other hand . . . doesn't show the category label.

The "easy" fix is to drop the `category` and then inline the `Draw: ` prefix to the command but that doesn't quite feel like it fits the UX among other apps. So it's _an_ option but not ideal.

What about changing the wording entirely? Maybe instead of `Edit Current Line`  something like `Edit Drawing`? Open to ideas if you have any opinion on the matter.

**Comment by hall** [comment]
Fixed in https://github.com/hall/draw/commit/c834596529269999812a1b9e41b6235163ba1dfd; will be in the next release.
